/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class top_oply_opuslib_OpusTool */

#ifndef _Included_top_oply_opuslib_OpusTool
#define _Included_top_oply_opuslib_OpusTool
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif
